import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PGliteWrapper from "./pglite-wrapper";
import TanstackProvider from "./tanstack-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Navbar from "@/components/navbar";
import { SidebarProvider } from "@/components/providers/sidebar";
import { LeftSidebar } from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[calc(100dvh)] w-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PGliteWrapper>
            <TanstackProvider>
              <SidebarProvider
                defaultOpen={true}
                className="grid h-dvh grid-rows-[auto_1fr]"
              >
                <div className="row-span-2 flex">
                  <LeftSidebar />
                  <main className="relative flex flex-1 overflow-auto">
                    <div className="grid flex-1">{children}</div>
                  </main>
                </div>
              </SidebarProvider>
            </TanstackProvider>
          </PGliteWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
